### ISSUE TITLE
Add support for LoggerExtensions.BeginScope method

### ISSUE THREAD

**Issue by jizc** [olsh/resharper-structured-logging#6]
Would love to see support for the `LoggerExtensions.BeginScope` method in Microsoft.Extensions.Logging:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.beginscope

**Comment by jizc** [comment]
Wow, fantastic! Thank you!

**Comment by iam-black** [comment]
Is it possible to support the following BeginScope usage?
![image](https://user-images.githubusercontent.com/8601553/118961384-f13f5c00-b96c-11eb-8355-d68f3cff0506.png)

**Comment by olsh** [comment]
Hi @iam-black 

Hrm, what do you mean by support? The properties are not templates. So the only analysis I can think of is properties naming validation, like
```csharp
using (_logger.BeginScope(new Dictionary<string, object>
{
  {"ConnectionId", connection.ConnectionId}, // valid
  {"customer_id", connection.CustomerId}, // invalid
}))
```

**Comment by iam-black** [comment]
Message template in the last line with _logger.LogInformation is marked with "Non-existent argument", but arguments are present in the scope.

**Comment by olsh** [comment]
Does this code works as expected? I tried it with Serilog and it doesn't work
```csharp
Log.Logger = new LoggerConfiguration()
	.WriteTo.Console()
	.CreateLogger();

using(LogContext.PushProperty("Name", "olsh"))
{
	Log.Information("Hello {Name}"); // Prints `Hello {Name}`
}
```

Which logger are you using under the hood?

**Comment by iam-black** [comment]
Serilog with Elasticsearch sink. The previous line is working fine.
![image](https://user-images.githubusercontent.com/8601553/118995154-95d29580-b98f-11eb-8cc6-7a8b7d6ed4ce.png)

**Comment by olsh** [comment]
Interesting, I'll take a look when I have spare time.

**Comment by olsh** [comment]
Hi @iam-black 

My bad, I forgot to add `.Enrich.FromLogContext()` in the logger configuration. Yes, your code should definitely work.

This is probably worth implementing, but this won't be easy because you should investigate the entire call stack to determine the context. I'll gladly accept PR.

Also, I'd like to mention that the main usage of the content is to avoid repetition and add context to messages. We are using Elastic for logging too, and we attach the context properties to log messages without rendering them in the templates. In other words, we don't put properties from scope to templates because they are attached anyway, and you can use them in Elastic filters.
